### ISSUE TITLE
Delish Url import issue 

### ISSUE THREAD

**Issue by mfarazGenetech** [hhursev/recipe-scrapers#695] opened 2022-12-06 11:38 UTC
I got an issue when i try to import instruction from delish and the error showing "'NoneType object has no attribute 'findAll'" How can i made changes in delish.py file to run smoothly
Waiting for your kind response.
Thanks,

**Comment by jayaddison** [comment] 2022-12-10 16:52
Thanks for reporting this @mfarazGenetech - closing this as a duplicate of #694 (did the upgrade work?)

**Closed by jayaddison** 2022-12-10 16:52 UTC

**Comment by mfarazGenetech** [comment] 2022-12-12 04:37
yes its working fine.
Thanks
