### ISSUE TITLE
Scraper Request - Aldi (Australia)

### ISSUE THREAD

**Issue by RavHilton** [hhursev/recipe-scrapers#1146] opened 2024-06-03 22:15 UTC
G'day,

I was wondering if someone could please make a scraper for the recipes (approx 400 recipes are available) on the []([](https://www.aldi.com.au/recipes/)) site:

https://www.aldi.com.au/recipes/main-meals-recipes/spinach-soup-recipe/
https://www.aldi.com.au/recipes/main-meals-recipes/sausage-and-zucchini-skewers-with-rice-salad-recipe/
https://www.aldi.com.au/recipes/main-meals-recipes/oregano-and-orange-roast-chicken-recipe/
https://www.aldi.com.au/baked-brie-honey-and-walnut-pita-recipe/
https://www.aldi.com.au/recipes/breakfast-recipes/cheesy-oats-with-brussels-sprouts-and-sweet-potato-recipe/

That last example there is *ABSOLUTELY* something I will try really soon...  :)

**Comment by jknndy** [comment] 2024-06-03 22:32
hello @RavHilton, this is being addressed in #1139, which is currently under review. If you're in a rush, you could download that fork, but otherwise, it will be merged in the not-too-distant future!

I'll be closing this issue with this comment as it is a duplicate of #1137 but be sure to keep an eye on that thread for updates!

Let us know if you run into any bugs once you get a chance to use it!

**Closed by jknndy** 2024-06-03 22:32 UTC
