### ISSUE TITLE
scraper.ingredients() not working for any recipe on Food.com - returns empty list

### ISSUE THREAD

**Issue by JimmyStrings** [hhursev/recipe-scrapers#596] opened 2022-09-05 14:41 UTC
Attempted code:

```
from recipe_scrapers import scrape_me
scraper = scrape_me('https://www.food.com/recipe/air-fryer-buffalo-wings-538687')
print(scraper.ingredients())

```
Running the above code returns an empty list: `[]`

This problem occurs for all recipes on the Food.com website. 

Python version: 3.8
Operating System: Windows 10

**Comment by cydanil** [comment] 2022-09-06 12:58
Hi @JimmyStrings,  
Could you try again?  
I tried the code you provided, but it work as expected and I could not reproduce the issue.  

I'm running the main branch of `recipe-scrapers`, and I tried both Python 3.8.10 and 3.9.5 on Ubuntu.

**Comment by JimmyStrings** [comment] 2022-09-06 17:04
Hi @cydanil,

I just tried running the code again in a Jupyter notebook via Anaconda. I assume I am also running the main branch of recipe-scrapers (?). I am still having the same problem: the code returns an empty list. See image below:

![image](https://user-images.githubusercontent.com/63973463/188696491-a89e4568-2a84-4912-b55e-ef9e0be278bc.png)

As you can see, I incorrectly stated my Python version in the above comment. I am actually using 3.9.7.

What am I missing?

**Comment by cydanil** [comment] 2022-09-06 18:22
Thanks.  
You're doing things right and should indeed get the ingredients.  

Could you try the following?  
```python
from recipe_scrapers import scrape_me  
scraper = scrape_me('https://www.food.com/recipe/air-fryer-buffalo-wings-538687')
print(scraper.schema.ingredients())
print(scraper.ingredients())
```

**Comment by cydanil** [comment] 2022-09-06 18:24
Could you also try different properties (eg. `title`, `author`, `instructions_list`) please?

**Comment by JimmyStrings** [comment] 2022-09-06 20:07
Hi @cydanil,

Please see the following results from your suggested tests:

![image](https://user-images.githubusercontent.com/63973463/188728637-0cd8f095-b09a-4c9e-b624-da4d3c56939f.png)

**Comment by JimmyStrings** [comment] 2022-09-06 20:08
I guess I can use `scraper.schema.ingredients()` for now?

**Comment by cydanil** [comment] 2022-09-07 07:11
You could, yes.  
But it seems to me that you're using an older version of `recipe-scrapers`.  
Could you try to update it? `scraper.instructions_list` was added in July in version 14.11.0 (the latest version is 14.13.0).

**Comment by JimmyStrings** [comment] 2022-09-07 21:01
Hi @cydanil,

You are right. I was indeed using an old version of recipe-scrapers.

I have now updated to 14.13.0 as you can see in this image: 
![image](https://user-images.githubusercontent.com/63973463/188975767-0d33ab21-ffd8-4446-bc24-4ddea532ee6c.png)

I then ran the same code again in my Jupyter notebook:

```
from recipe_scrapers import scrape_me  
scraper = scrape_me('https://www.food.com/recipe/air-fryer-buffalo-wings-538687')
print(scraper.ingredients())
```

And unfortunately, it still returns an empty list: `[]`
I also tested `print(scraper.instructions_list())`and it errored: `AttributeError: 'Food' object has no attribute 'instructions_list'`

This makes me think that my Jupyter notebook is not using the updated package for some reason, despite me confirming the updated package in cmd window. 

I am relatively inexperienced with this, so it's possible I have made a mistake somewhere. However, it seems that this is probably not an issue with the package itself. More likely to be an issue with my local environment?

**Comment by bfcarpio** [comment] 2022-10-12 06:43
Can you try doing it straight in terminal without jupyter?

Steps similar to:
1. Create a brand new venv (just good habits)
2. `pip install recipe-scrapers`
3. `python`
4. `from recipe_scrapers import scrape_me`
5. `scraper = scrape_me('https://www.food.com/recipe/air-fryer-buffalo-wings-538687')`
6. `print(scraper.ingredients())`

This way you can isolate jupyter and the package itself. 

I'm going to close this since there doesn't seem to be any new information and there's a good chance this is not related to the package. Feel free to reopen and continue discussion.

**Closed by bfcarpio** 2022-10-12 06:43 UTC
Labels: bug

**Comment by JimmyStrings** [comment] 2022-10-20 22:38
Thanks for the suggestion @bfcarpio. I hadn't used venvs before so this was a good learning experience. I managed to update the package to 14.2 and got my project working in a  venv. Thanks again for your help!
