### ISSUE TITLE
www.finedininglovers.com returns empty strings

### ISSUE THREAD

**Issue by smilerz** [hhursev/recipe-scrapers#366] opened 2021-03-23 14:40 UTC
**Pre-filing checks**

- [x] I have searched for open issues that report the same problem
- [x] I have checked that the bug affects the latest version of the library

**The URL of the recipe(s) that are not being scraped correctly**

- https://www.finedininglovers.com/article/black-forest-cake-recipe

**The version of Python you're using**

3.9.1

**The operating system of your environment**

Windows 10

**The results you expect to see**

non-empty results

**The results (including any Python error messages) that you are seeing**
scrape.schema.data returns {}

Can you write Python and would you like to help fix the scraper yourself?  We'd be glad for your assistance!  We can provide you with guidance and code review in return.  If so, tick any of the relevant boxes below:

- [ ] I'd like to try fixing this scraper myself
- [ ] I'd like guidance to help me develop a fix
- [x] I'd prefer if the `recipe-scrapers` team try to fix this

**Comment by bfcarpio** [comment] 2021-03-23 18:43
Thank you @smilerz for notifying us. I did some quick testing and came up with some additional notes:
+ public functions (`instructions()`) also return empty values
+ Opening the `testhtml` file leads to a CSS-less based page.

It seems like this website might have updated.

**Comment by vabene1111** [comment] 2022-09-30 14:28
ok it appears that the above link is an "article" not a recipe (see url schema).

articles dont have many fields recipes have, i will add some try blocks so that articles provide as much data as possible.

PR will follow tomorrow.

**Comment by jayaddison** [comment] 2022-09-30 16:52
Nice, thank you for looking into this @vabene1111.  Pages that have type `Article` seem to be a fairly frequent issue.

I have one or two suggestions for the code based on f883dcc25a1d189ee2ed1deec1ab4e8c8cc4e6fa - let me know if you'd appreciate any early feedback, or I can wait and provide commentary when the pull request is ready.

**Comment by vabene1111** [comment] 2022-09-30 16:56
hey @jayaddison, thanks for the feedback. I would love to get feedback on the code, I made many assumptions because I wasn't sure on how you like to handle things. 

For example I dont really know if you prefer to have functions raise exceptions or if issues should be handled gracefully for example by returning 0 for a yield or servings. Let me know whatever needs to be changed or how you prefer things.

**Comment by jayaddison** [comment] 2022-09-30 18:09
Cool - yep, we should document these things as developer guidance.

The items I'm thinking about from a first-pass are:

- Scrapers shouldn't expose public methods that aren't available on other scrapers, so the [`is_article`](https://github.com/vabene1111/recipe-scrapers/commit/f883dcc25a1d189ee2ed1deec1ab4e8c8cc4e6fa#diff-25f0a984fd9046fdda3b4c24b5301011caa55ae9b4c5c731542cb95643c828b7R11) method should be considered private/internal (suggestion: rename to `_is_article`)

- Returning `0` can be a bit of a code smell - so in the [yields and servings](https://github.com/vabene1111/recipe-scrapers/commit/f883dcc25a1d189ee2ed1deec1ab4e8c8cc4e6fa#diff-25f0a984fd9046fdda3b4c24b5301011caa55ae9b4c5c731542cb95643c828b7R23-R30) cases you mention, I reckon that `None` is probably what we want (so the scraper responds with "empty timing/servings" instead of "recipe requires zero time / produces zero servings")

- We provide [settings](https://github.com/hhursev/recipe-scrapers/blob/442a035a53da212df18a98ccbae175b14aedbf31/recipe_scrapers/settings/default.py#L23-L40) for callers to decide how they want exceptions to be handled, so -- unless there's a good reason -- we probably _shouldn't_ catch and return a different value (as in [this `lecker.de` example](https://github.com/vabene1111/recipe-scrapers/commit/374d3101814a713b17aa142d7af5dd12e897afd7#diff-5f3aedc536dd4665f0778c2ff8666f6d1e249add0feead006d71498e9ef66d20R32-R33))

(also a tiny nitpick: [typo here](https://github.com/vabene1111/recipe-scrapers/commit/f883dcc25a1d189ee2ed1deec1ab4e8c8cc4e6fa#diff-25f0a984fd9046fdda3b4c24b5301011caa55ae9b4c5c731542cb95643c828b7R13))

**Comment by vabene1111** [comment] 2022-10-01 08:18
awesome, thanks for the feedback. All of that makes perfect sense and i will change everything accordingly!

**Comment by jayaddison** [comment] 2022-10-19 14:54
Hey @smilerz - @vabene1111 took a look at this, and unfortunately my response after learning more about the issue is that I'm not convinced that this category of articles on finedininglovers is practical to support.  Maybe that's misguided, I'm not sure - feel free to disagree; #612 includes some discussion and the conclusion so far.

At the moment I feel like there's a bunch of work to do to simplify and streamline the scraper development process (and maintenance and review process).  It's not bad at the moment but it'd be nice to support a more rapid stream of changes and contributions with higher quality and testing -- and my sense is that doing that is going to require restructuring the internals of the library a bit.

Which means I'm trying harder (but not always managing) to catch changes that might make it harder to do that restructuring.

Closing for now, but further feedback and help appreciated!

**Closed by jayaddison** 2022-10-19 14:54 UTC
Labels: bug
