### ISSUE TITLE
Please Add this link  https://www.bingingwithbabish.com/

### ISSUE THREAD

**Issue by mfarazGenetech** [hhursev/recipe-scrapers#696] opened 2022-12-07 06:42 UTC
New site : https://www.bingingwithbabish.com/

Please add this site link
Thanks

**Comment by jayaddison** [comment] 2022-12-07 10:46
Thanks for the suggestion, @mfarazGenetech!  This is a duplicate of #425 - I can't promise when support will be added, but it should be at some point.

A request: when possible, please search for existing bug reports before opening new ones (on this project, and others).

**Closed by jayaddison** 2022-12-07 10:46 UTC

**Comment by mfarazGenetech** [comment] 2022-12-07 11:01
Thank you so much,  
and sorry for the inconvenience I'll double check existing bug report before opening the new ones.
