### ISSUE TITLE
Site Request

### ISSUE THREAD

**Issue by HWMNBG** [hhursev/recipe-scrapers#630] opened 2022-10-11 06:40 UTC
Would it be possible to have taste.com.au added? 

https://www.taste.com.au/recipes/parmesan-crumbed-baked-fish/91886785-7c58-4492-8f61-3843d9901e80?r=quickeasy&c=eacc9e75-1ca0-47f1-85b9-f5bc1534fb3f/30%20minute%20meals&h=Quick%20%20easy

Thanks!

**Comment by jayaddison** [comment] 2022-10-12 14:29
Hi @HWMNBG - I'm closing this as a duplicate of #359.  There's a suggestion in there about trying out the `wild_mode` option when scraping; that might allow you to get some/all of the information you're looking for.

**Closed by jayaddison** 2022-10-12 14:29 UTC
