### ISSUE TITLE
[suggestion] Supporting sections in recipes

### ISSUE THREAD

**Issue by sbdchd** [hhursev/recipe-scrapers#587] opened 2022-08-16 04:04 UTC
There exists a scraper for the nytimes cooking site but it doesn't include sections in the output data.

For instance, the ingredients in https://cooking.nytimes.com/recipes/1018023-baked-fish-and-chips are split into two sections, `Tatar sauce` and `Fish and chips`.

Not really sure what the schema would look like for the scraped recipe, but was wondering if you'd be open to a PR that adds section metadata?

**Comment by jayaddison** [comment] 2022-10-12 14:30
Hi @sbdchd - I'm closing this as a duplicate of #301.  There's a prototype implementation arriving soon for at least one scraper, so this should be possible soon.  It'll be optional -- only some scrapers will support it.

**Closed by jayaddison** 2022-10-12 14:30 UTC
Labels: enhancement
